spring:
  datasource:
    url: jdbc:h2:mem:jackpotdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual
    consumer:
      group-id: jackpot-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.sporty.jackpot.domain.model"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max.block.ms: 3000
        request.timeout.ms: 3000
        delivery.timeout.ms: 5000
        metadata.max.age.ms: 1000
        spring.json.trusted.packages: "*"
    admin:
      fail-fast: false
      auto-create: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

resilience4j:
  circuitbreaker:
    instances:
      jackpotEvaluate:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 3
  ratelimiter:
    instances:
      evaluateRateLimit:
        limit-for-period: 100
        limit-refresh-period: 1s
        timeout-duration: 0

logging:
  level:
    com.sporty.jackpot: DEBUG
